name       : spread-sheet-widget
version    : 0.3
release    : 1
source     :
    - ftp://alpha.gnu.org/gnu/ssw/spread-sheet-widget-0.3.tar.gz : 1e2dc2c6fb8f3718188cec635b6601ba453b4bb3683ccc67cddef825a0f723c1
license    : GPL-3.0-or-later
component  : programming.library
summary    : GNU Spread Sheet Widget
description: |
    GNU Spread Sheet Widget is a library for Gtk+ which provides a widget for viewing and manipulating 2 dimensional tabular data in a manner similar to many popular spread sheet programs.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check